"""Stage D — format split curated records into instruction/response JSONL.

Takes `data/curated/split_train.jsonl` / `split_val.jsonl` (`split.py`'s
output — curated-shape records, already partitioned) and emits
`data/splits/train.jsonl` / `val.jsonl`: the actual fine-tuning-ready
JSONL, one `{"instruction": ..., "response": ...}` object per line.

**JSONL shape.** `instruction` is the patient's (redacted) clinical note
text — a string. `response` is a JSON-formatted **string** (not a nested
object) containing `date_of_birth`, `diagnoses`, `medications`, `vitals` —
a string, not a nested object, because fine-tuning trains the model to
generate *text*: the target the model must learn to produce is itself the
serialized JSON, matching how it would actually need to emit structured
output at inference time. `patient_id` and any curation bookkeeping tags
(`rebalance_duplicate_of`, etc.) are dropped from `response` — they're
pipeline metadata, not something a note-extraction model should learn to
predict. `response` includes `date_of_birth` but not `note_date`: DOB was
one of `extractor.py`'s actual LLM-extracted fields (Stage B's schema), so
keeping it here mirrors the real task being distilled; `note_date` was
never an extraction target — it's pipeline-assigned metadata about when the
note was generated, not a fact the model reads out of the note's body.
`patient_name` isn't in `response` either, for the obvious reason: it was
permanently dropped by `redact.py`, not just shifted.

**Instruction = redacted note text, via targeted find-and-replace — not
generic free-text de-identification.** Per CLAUDE.md's Resolved decisions
#8: since these notes were generated by this repo's own code, the exact
ground-truth PHI strings inserted into each one are already known from
`data/generated/fhir_bundles.json` (the same source `redact.py` draws
from), so redacting them is a matter of substituting known exact strings,
not inferring PHI from arbitrary prose (a much harder, out-of-scope
problem). Substituted per patient:

- the patient's full name (as it literally appears: `"{given} {family}"`,
  matching `generate_notes.py`'s own construction) -> the placeholder
  `"[PATIENT NAME]"`. Unlike the structured `patient_name` field (dropped
  entirely by `redact.py`, since a masked-but-present value had no
  downstream benefit there), free-text prose needs *something* in its
  place to stay grammatically readable as a training instruction — so a
  placeholder is used here specifically for that reason, not for
  consistency with the structured field's treatment.
- the patient's MRN value (e.g. `"MRN334053"`, exactly as
  `generate_fhir.py` generated it) -> `"[MRN]"`, and the patient's full
  address string (exactly as `generate_notes.py`'s own `_address_str`
  builds it) -> `"[ADDRESS]"` — same "known exact string, from the same
  FHIR source" pattern as the name, and the same placeholder-not-strip
  reasoning (prose needs something in the value's place). Neither field
  has temporal meaning, so unlike the dates below there's no shift to
  apply — this mirrors `redact.py`'s own treatment of these two fields
  (full removal, not shifting). Both are skipped when absent (messy
  generation can drop either from the Patient resource).
- `birthDate` -> `redact.shift_date(patient_id, "dob", ...)`.
- every Condition `onsetDateTime`, Observation `effectiveDateTime`,
  MedicationStatement `effectiveDateTime`, and the note's own `note_date`
  -> `redact.shift_date(patient_id, "visit", ...)`. These all share the
  **same** `visit` category (and therefore the same per-patient offset) as
  `redact.py` already established, so a shifted date appearing in the note
  body and the same date field in the structured response always agree —
  reusing `redact.shift_date` directly (not reimplementing the shift math)
  is what guarantees that, rather than merely aiming for it.

  Not every one of these dates actually appears in rendered note text
  today (`generate_notes.py`'s vitals/meds sections show values, not
  dates) — all are still substituted defensively so a future note-template
  change that surfaces one doesn't silently leak it.

**Why one combined regex pass, not sequential `.replace()` calls.**
Multiple distinct dates for the same patient are being replaced
simultaneously. Sequential `str.replace()` calls risk a later rule
matching text a previous rule just *produced* (e.g. rule A's shifted output
happens to equal rule B's original search string) — a real correctness bug
for simultaneous substitution, not just a style preference. Building one
compiled regex (alternation over all original strings for that patient) and
substituting via a single `re.sub` pass guarantees every match is resolved
against the *original* text, once, matching CLAUDE.md's general "single
compiled pass over naive repeated passes" convention for a genuine
correctness reason here, not just performance.

**Duplicates share their original's note/bundle.** A `rebalance.py`
duplicate (`-dupN` patient_id) has no note of its own — `split.py`'s
`original_patient_id()` helper (imported here) is reused to resolve every
record back to the patient whose note/bundle it should actually draw from,
so a duplicate's instruction is built from the *same* note as its original
(consistent with them being near-identical training examples by design).

**Leakage check is per-patient, not corpus-wide.** At 100 patients, a
corpus-wide "does this real string appear *anywhere* in the output" scan
produced a false positive: patient A's real DOB coincidentally equaled
patient B's own correctly-shifted DOB (a birthday-paradox effect — 100
independent per-patient offsets across a ~66-year birth-date range makes
some coincidental collision likely, not a bug). That collision discloses
nothing about patient A — the string appears only as patient B's own
(properly de-identified) date, with no link back to A's identity anywhere
in the data. So the check that actually matters is scoped per patient:
does *record X's own* real name/DOB/mrn/address appear in *record X's own*
example — not whether that string appears anywhere in the whole corpus.
"""

import argparse
import json
import re
from pathlib import Path

from curation.redact import shift_date
from generation.fhir_common import group_bundle_entries
from split import original_patient_id, read_records

DATA_DIR = Path(__file__).resolve().parent / "data"
NOTES_PATH = DATA_DIR / "generated" / "clinical_notes.jsonl"
BUNDLES_PATH = DATA_DIR / "generated" / "fhir_bundles.json"
REDACTED_PATH = DATA_DIR / "curated" / "redacted.jsonl"
SPLIT_TRAIN_PATH = DATA_DIR / "curated" / "split_train.jsonl"
SPLIT_VAL_PATH = DATA_DIR / "curated" / "split_val.jsonl"
TRAIN_OUT = DATA_DIR / "splits" / "train.jsonl"
VAL_OUT = DATA_DIR / "splits" / "val.jsonl"

NAME_PLACEHOLDER = "[PATIENT NAME]"
MRN_PLACEHOLDER = "[MRN]"
ADDRESS_PLACEHOLDER = "[ADDRESS]"


def _mrn(patient):
    """Mirrors generate_notes.py's _mrn — duplicated rather than imported,
    same reasoning as elsewhere in this codebase: that module's own
    script-relative import isn't safely importable from here."""
    identifiers = patient.get("identifier")
    return identifiers[0]["value"] if identifiers else None


def _address_str(patient):
    """Mirrors generate_notes.py's _address_str exactly, so the string
    being searched for matches the string actually written into note text."""
    addresses = patient.get("address")
    if not addresses:
        return None
    addr = addresses[0]
    street = ", ".join(addr.get("line", []))
    city = addr.get("city", "")
    state = addr.get("state", "")
    postal_code = addr.get("postalCode", "")
    return f"{street}, {city}, {state} {postal_code}".strip()


def load_notes(path):
    return {json.loads(l)["patient_id"]: json.loads(l) for l in path.open() if l.strip()}


def load_bundles(path):
    bundles = json.loads(path.read_text())
    by_patient = {}
    for bundle in bundles:
        patient, _, _, _ = group_bundle_entries(bundle)
        by_patient[patient["id"]] = bundle
    return by_patient


def build_replacements(patient_id, bundle, note_date_str):
    """Map of exact original string -> redacted string, for one patient."""
    patient, conditions, medications, observations = group_bundle_entries(bundle)
    replacements = {}

    name = patient.get("name", [{}])[0]
    full_name = f"{' '.join(name.get('given', []))} {name.get('family', '')}".strip()
    if full_name:
        replacements[full_name] = NAME_PLACEHOLDER

    mrn = _mrn(patient)
    if mrn:
        replacements[mrn] = MRN_PLACEHOLDER

    address = _address_str(patient)
    if address:
        replacements[address] = ADDRESS_PLACEHOLDER

    birth_date = patient["birthDate"]
    replacements[birth_date] = shift_date(patient_id, "dob", birth_date)

    visit_dates = set()
    for c in conditions:
        if c["onset"]:
            visit_dates.add(c["onset"])
    for m in medications:
        if m["effective"]:
            visit_dates.add(m["effective"])
    for readings in observations.values():
        for r in readings:
            if r["date"]:
                visit_dates.add(r["date"])
    if note_date_str:
        visit_dates.add(note_date_str)

    for d in visit_dates:
        replacements[d] = shift_date(patient_id, "visit", d)

    return replacements


def redact_note_text(note_text, replacements):
    if not replacements:
        return note_text
    pattern = re.compile("|".join(re.escape(k) for k in sorted(replacements, key=len, reverse=True)))
    return pattern.sub(lambda m: replacements[m.group(0)], note_text)


def build_response(record):
    return json.dumps({
        "date_of_birth": record["date_of_birth"],
        "diagnoses": record["diagnoses"],
        "medications": record["medications"],
        "vitals": record["vitals"],
    })


def format_record(record, notes_by_patient, bundles_by_patient):
    base_id = original_patient_id(record)
    note = notes_by_patient[base_id]
    bundle = bundles_by_patient[base_id]

    replacements = build_replacements(base_id, bundle, note["note_date"])
    instruction = redact_note_text(note["note_text"], replacements)
    response = build_response(record)

    return {"instruction": instruction, "response": response}


def write_jsonl(examples, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        for ex in examples:
            f.write(json.dumps(ex) + "\n")


def main():
    parser = argparse.ArgumentParser(description="Format split curated records into instruction/response JSONL.")
    parser.add_argument("--train-in", type=Path, default=SPLIT_TRAIN_PATH)
    parser.add_argument("--val-in", type=Path, default=SPLIT_VAL_PATH)
    parser.add_argument("--train-out", type=Path, default=TRAIN_OUT)
    parser.add_argument("--val-out", type=Path, default=VAL_OUT)
    args = parser.parse_args()

    notes_by_patient = load_notes(NOTES_PATH)
    bundles_by_patient = load_bundles(BUNDLES_PATH)

    train_records = list(read_records(args.train_in))
    val_records = list(read_records(args.val_in))

    train_examples = [format_record(r, notes_by_patient, bundles_by_patient) for r in train_records]
    val_examples = [format_record(r, notes_by_patient, bundles_by_patient) for r in val_records]

    write_jsonl(train_examples, args.train_out)
    write_jsonl(val_examples, args.val_out)

    print(f"Wrote {len(train_examples)} examples to {args.train_out}")
    print(f"Wrote {len(val_examples)} examples to {args.val_out}")

    # --- Verification -----------------------------------------------------

    redacted_by_patient = {r["patient_id"]: r for r in read_records(REDACTED_PATH)}

    print("\n--- sample before/after + date-consistency check ---")
    for record in (train_records + val_records)[:3]:
        base_id = original_patient_id(record)
        note = notes_by_patient[base_id]
        example = format_record(record, notes_by_patient, bundles_by_patient)

        print(f"\npatient_id={record['patient_id']} (base={base_id})")
        print("ORIGINAL note text:")
        print(note["note_text"])
        print("\nREDACTED instruction:")
        print(example["instruction"])

        curated_dob = redacted_by_patient[base_id]["date_of_birth"]
        curated_note_date = redacted_by_patient[base_id]["note_date"]
        dob_ok = curated_dob in example["instruction"]
        note_date_ok = curated_note_date in example["instruction"]
        print(f"\ncurated date_of_birth={curated_dob!r} appears in instruction: {dob_ok}")
        print(f"curated note_date={curated_note_date!r} appears in instruction: {note_date_ok}")
        if not (dob_ok and note_date_ok):
            print("MISMATCH: instruction dates do not match redact.py's shifted dates for this patient.")

    print("\n--- leakage grep: does any example contain ITS OWN patient's real (unshifted) name/DOB/mrn/address? ---")
    leaks = []
    for record in train_records + val_records:
        base_id = original_patient_id(record)
        patient, _, _, _ = group_bundle_entries(bundles_by_patient[base_id])
        example = format_record(record, notes_by_patient, bundles_by_patient)
        text = example["instruction"] + example["response"]

        name = patient.get("name", [{}])[0]
        full_name = f"{' '.join(name.get('given', []))} {name.get('family', '')}".strip()
        if full_name and full_name in text:
            leaks.append(f"real name {full_name!r} leaked into {record['patient_id']}'s own example")
        if patient["birthDate"] in text:
            leaks.append(f"real DOB {patient['birthDate']!r} leaked into {record['patient_id']}'s own example")
        mrn = _mrn(patient)
        if mrn and mrn in text:
            leaks.append(f"real mrn {mrn!r} leaked into {record['patient_id']}'s own example")
        address = _address_str(patient)
        if address and address in text:
            leaks.append(f"real address {address!r} leaked into {record['patient_id']}'s own example")

    if leaks:
        print(f"LEAKAGE FOUND ({len(leaks)}):")
        for leak in leaks:
            print(f"  {leak}")
    else:
        print(f"No example leaks its own patient's real (unshifted) name/DOB/mrn/address "
              f"({len(train_records) + len(val_records)} records checked).")


if __name__ == "__main__":
    main()
